// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef FractalTreeUI_h
#define FractalTreeUI_h
#include <FL/Fl.H>
#include "FractalTree.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#endif
