// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef ScribbleUI_h
#define ScribbleUI_h
#include <FL/Fl.H>
#include <cstdlib>
#include "ScribbleBox.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#endif
