// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef clock_h
#define clock_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Clock.H>
#include <FL/Fl_Button.H>

class Clock {
public:
  Clock();
  Fl_Double_Window *win;
private:
  void cb_Quit_i(Fl_Button*, void*);
  static void cb_Quit(Fl_Button*, void*);
};
#endif
