// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "clock.h"

int main(int argc, char **argv) {
  Clock* c = new Clock();
c->win->show();
  return Fl::run();
}

void Clock::cb_Quit_i(Fl_Button* o, void*) {
  o->window()->hide();
}
void Clock::cb_Quit(Fl_Button* o, void* v) {
  ((Clock*)(o->parent()->user_data()))->cb_Quit_i(o,v);
}

Clock::Clock() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = win = new Fl_Double_Window(350, 250);
    w = o;
    o->user_data((void*)(this));
    new Fl_Clock(25, 25, 230, 210);
    { Fl_Button* o = new Fl_Button(265, 120, 70, 20, "Quit");
      o->callback((Fl_Callback*)cb_Quit);
    }
    o->end();
  }
}
