// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef SierpinskiUI_h
#define SierpinskiUI_h
#include <FL/Fl.H>
#include <cstdlib>
#include "Sierpinski.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#endif
