// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "SierpinskiUI.h"

static void cb_Quit(Fl_Button*, void*) {
  exit(0);
}

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(400, 400, "Sierpinski");
    w = o;
    { Fl_Button* o = new Fl_Button(305, 365, 90, 30, "Quit");
      o->tooltip("Quit Sierpinksi Demo");
      o->down_box(FL_DOWN_BOX);
      o->labelsize(18);
      o->callback((Fl_Callback*)cb_Quit);
    } // Fl_Button* o
    { Sierpinski* o = new Sierpinski(25, 28, 350, 327, "Sierpinksi Gasket");
      o->box(FL_EMBOSSED_FRAME);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_TOP);
      o->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(o);
    } // Sierpinski* o
    o->size_range(100, 100);
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
