// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef ClientUI_h
#define ClientUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>
void appendOutput(const char* txt);
void updateConnectStatus();
int connectToggle();
#endif
