// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef ServerUI_h
#define ServerUI_h
#include <FL/Fl.H>
void appendOutput(const char* txt);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Text_Display.H>
void updateConnectStatus();
#endif
