// generated by Fast Light User Interface Designer (fluid) version 1.0104

#include "BankInterestUI.h"
#include <FL/fl_message.H>
#include "BankInterest.h"
static float widthdrawals[4];

void update_balance() {
  widthdrawals[0] = w1->value();
widthdrawals[1] = w2->value();
widthdrawals[2] = w3->value();
widthdrawals[3] = w4->value();
balance->value(
calc_balance(init_bal->value(), rate->value(), widthdrawals, 4));
}

Fl_Value_Input *init_bal=(Fl_Value_Input *)0;

static void cb_init_bal(Fl_Value_Input*, void*) {
  update_balance();
}

Fl_Value_Input *rate=(Fl_Value_Input *)0;

static void cb_rate(Fl_Value_Input*, void*) {
  update_balance();
}

Fl_Value_Input *w1=(Fl_Value_Input *)0;

static void cb_w1(Fl_Value_Input*, void*) {
  update_balance();
}

Fl_Value_Input *w2=(Fl_Value_Input *)0;

static void cb_w2(Fl_Value_Input*, void*) {
  update_balance();
}

Fl_Value_Input *w3=(Fl_Value_Input *)0;

static void cb_w3(Fl_Value_Input*, void*) {
  update_balance();
}

Fl_Value_Input *w4=(Fl_Value_Input *)0;

static void cb_w4(Fl_Value_Input*, void*) {
  update_balance();
}

Fl_Value_Output *balance=(Fl_Value_Output *)0;

static void cb_Ok(Fl_Button*, void*) {
  fl_message("Press Escape to Quit");
}

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(320, 265, "BankInterest");
    w = o;
    o->tooltip("A simple bank interest calculator.");
    { Fl_Value_Input* o = init_bal = new Fl_Value_Input(165, 20, 60, 25, "Starting balance:");
      o->tooltip("How much money is initially in your account");
      o->maximum(9999);
      o->callback((Fl_Callback*)cb_init_bal);
    }
    { Fl_Value_Input* o = rate = new Fl_Value_Input(165, 45, 45, 25, "Interest rate:");
      o->tooltip("Enter \"12\" for an account earning twelve percent.");
      o->callback((Fl_Callback*)cb_rate);
    }
    { Fl_Value_Input* o = w1 = new Fl_Value_Input(217, 75, 55, 25, "First Quarter widthdrawal:");
      o->tooltip("How much to take out after the first quarter");
      o->callback((Fl_Callback*)cb_w1);
    }
    { Fl_Value_Input* o = w2 = new Fl_Value_Input(217, 100, 55, 25, "Second Quarter widthdrawal:");
      o->tooltip("How much to take out after the second quarter");
      o->callback((Fl_Callback*)cb_w2);
    }
    { Fl_Value_Input* o = w3 = new Fl_Value_Input(217, 125, 55, 25, "Third Quarter widthdrawal:");
      o->tooltip("How much to take out after the third quarter");
      o->callback((Fl_Callback*)cb_w3);
    }
    { Fl_Value_Input* o = w4 = new Fl_Value_Input(217, 150, 55, 25, "Fourth Quarter widthdrawal:");
      o->tooltip("How much to take out after the fourth quarter");
      o->callback((Fl_Callback*)cb_w4);
    }
    { Fl_Value_Output* o = balance = new Fl_Value_Output(165, 205, 80, 25, "Ending Balance: ");
      o->tooltip("How much money is left in the account");
      o->maximum(9999);
      o->step(0.01);
    }
    { Fl_Button* o = new Fl_Button(245, 230, 70, 30, "Ok bye!");
      o->callback((Fl_Callback*)cb_Ok);
    }
    o->end();
  }
  w->show(argc, argv);
  return Fl::run();
}
