// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef BankInterestUI_h
#define BankInterestUI_h
#include <FL/Fl.H>
void update_balance();
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *init_bal;
extern Fl_Value_Input *rate;
extern Fl_Value_Input *w1;
extern Fl_Value_Input *w2;
extern Fl_Value_Input *w3;
extern Fl_Value_Input *w4;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *balance;
#include <FL/Fl_Button.H>
#endif
